# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TronWebDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TronWebDemo
  pod 'SnapKit', '~> 5.6.0'
  pod 'TronWeb', '~> 1.1.4'
end
